const test = require('node:test');
const assert = require('node:assert/strict');
test('staleness follows the oldest visible scan, time, dismissal and scan lifecycle', async (t) => {
  const { createStaleNotice, STALE_AFTER } = await import('../renderer/stale-notice.mjs');
  t.mock.timers.enable({ apis: ['Date'], now: 100000000 });
  const host = (host, age) => ({ host, report: { scannedAt: new Date(Date.now() - age).toISOString() } });
  const workspace = { snapshot: { hostFilter: null, hosts: [host('', 1800000), host('build', 7200000)] }, refresh() {} };
  const elements = new Map();
  const element = (s) => { if (!elements.has(s)) elements.set(s, { contains: () => false }); return elements.get(s); };
  let tick, focus, cleared = 0;
  const clock = { setTimeout(fn) { tick = fn; }, clearTimeout() { cleared++; }, addEventListener(_, fn) { focus = fn; }, removeEventListener() {} };
  const view = createStaleNotice({ document: { querySelector: element }, workspace, clock });
  view.render();
  assert.equal(element('#stale-note').hidden, false);
  assert.match(element('#stale-text').textContent, /^build:/);
  element('#stale-dismiss').onclick();
  assert.equal(element('#stale-note').hidden, true);
  workspace.snapshot.hostFilter = '';
  view.render();
  assert.equal(element('#stale-note').hidden, true);
  t.mock.timers.tick(STALE_AFTER / 2);
  tick();
  assert.equal(element('#stale-note').hidden, false, 'a live scan ages too');
  workspace.snapshot.busy = true; focus();
  assert.equal(element('#stale-note').hidden, true);
  workspace.snapshot.busy = false;
  workspace.snapshot.setupRequired = true; focus();
  assert.equal(element('#stale-note').hidden, true);
  workspace.snapshot.setupRequired = false;
  workspace.snapshot.hosts[0] = host('', 0); focus();
  assert.equal(element('#stale-note').hidden, true, 'refresh clears the notice');
  workspace.snapshot.hostFilter = 'build'; focus();
  assert.equal(element('#stale-note').hidden, true, 'dismissal survives host switches');
  workspace.snapshot.hosts[1] = host('build', 7200001); focus();
  assert.equal(element('#stale-note').hidden, false, 'another scan can warn again');
  view.dispose(); assert.ok(cleared);
});
