#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const packageRoot = path.dirname(require.resolve("lucide-static/package.json"));

// Keep Arbor's public names stable. Both settings controls deliberately use
// the gear; undo-2 means restore, refresh-cw means rescan, and the column chart
// represents the daily cleanup statistics (not a trend/line chart).
const icons = {
  branch: "git-branch",
  merge: "git-merge",
  monitor: "monitor",
  server: "server",
  chevrons: "chevrons-up-down",
  "chevron-down": "chevron-down",
  "chevron-right": "chevron-right",
  more: "ellipsis",
  "check-circle": "circle-check",
  settings: "settings",
  sliders: "settings",
  refresh: "refresh-cw",
  undo: "undo-2",
  check: "check",
  search: "search",
  sort: "chevrons-up-down",
  close: "x",
  trash: "trash-2",
  folder: "folder",
  info: "info",
  warning: "triangle-alert",
  edit: "pencil",
  external: "external-link",
  sun: "sun",
  moon: "moon",
  plus: "plus",
  minus: "minus",
  "arrow-up": "arrow-up",
  "arrow-down": "arrow-down",
  chart: "chart-column-increasing",
  copy: "copy",
  "panel-left-close": "panel-left-close",
  "panel-left-open": "panel-left-open",
};

function generate() {
  const version = require(path.join(packageRoot, "package.json")).version;
  const pinned = require("../package.json").devDependencies["lucide-static"];
  if (version !== pinned) throw new Error(`Expected lucide-static ${pinned}, installed ${version}`);
  const paths = {};
  for (const [name, source] of Object.entries(icons)) {
    const svg = fs.readFileSync(path.join(packageRoot, "icons", `${source}.svg`), "utf8");
    const match = svg.match(/<svg\b([^>]*)>([\s\S]*?)<\/svg>/);
    if (!match) throw new Error(`Invalid Lucide SVG: ${source}`);
    for (const attribute of ['viewBox="0 0 24 24"', 'fill="none"', 'stroke="currentColor"', 'stroke-width="2"', 'stroke-linecap="round"', 'stroke-linejoin="round"'])
      if (!match[1].includes(attribute)) throw new Error(`Unexpected ${source} drawing attributes: ${attribute}`);
    // Preserve every byte between the SVG tags, including whitespace.
    paths[name] = match[2];
  }
  return {
    "desktop/renderer/icons.generated.mjs":
      `// Generated by npm run icons from lucide-static ${version}. Do not edit.\n` +
      `// ISC and Feather MIT notices: THIRD_PARTY_NOTICES.txt in the app resources.\n` +
      `export const iconPaths = Object.freeze(${JSON.stringify(paths, null, 2)});\n`,
    "THIRD_PARTY_NOTICES.txt":
      `Lucide icons (lucide-static ${version}) — https://lucide.dev\n\n` +
      fs.readFileSync(path.join(packageRoot, "LICENSE"), "utf8"),
  };
}

if (require.main === module) {
  const check = process.argv.includes("--check");
  for (const [relative, content] of Object.entries(generate())) {
    const file = path.join(root, relative);
    if (check) {
      if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content)
        throw new Error(`${relative} is out of date; run npm run icons`);
    } else fs.writeFileSync(file, content);
  }
}
module.exports = { icons, generate };
